### ISSUE TITLE
Documentation warnings and errors

### ISSUE THREAD

**Issue by merkys** [askv4694/ewasvisual#3]
Running `R CMD check .` on Ubuntu 20.04 yields the following warnings and errors about the documentation:
```
* checking for code/documentation mismatches ... WARNING
Functions or methods with usage in documentation object 'hello' but not in code:
  ‘hello’

* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'getVisNetwork'
  ‘len’
Documented arguments not in \usage in documentation object 'getVisNetwork':
  ‘name’

Undocumented arguments in documentation object 'traitTable'
  ‘data’
Documented arguments not in \usage in documentation object 'traitTable':
  ‘dara’

Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... WARNING
Warning: parse error in file 'lines':
49: unexpected symbol
104: data <- filterBy(data, "Probe.id", c("cg02609880", "cg06874172"))
105: data <- filterBy(data, "Study.id", c("ES00034, "ES00035
                                                     ^
* checking examples ... ERROR
Running examples in ‘ewasvisual-Ex.R’ failed
The error most likely occurred in:

> ### Name: appendMatrixSize
> ### Title: Append matrix rows
> ### Aliases: appendMatrixSize
> 
> ### ** Examples
> 
> data <- appendMatrixSize(col, dataFrame)
Error in unique.default(col) : unique() applies only to vectors
Calls: appendMatrixSize -> %in% -> unique -> unique.default
Execution halted
* checking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
```

**Comment by merkys** [comment]
Not everything is fixed as of 7074efd41fb2fca551523514d5b5ad22b7213535. The following error remains:
```
* checking examples ... ERROR
Running examples in ‘ewasvisual-Ex.R’ failed
The error most likely occurred in:

> ### Name: appendMatrixSize
> ### Title: Append matrix rows
> ### Aliases: appendMatrixSize
> 
> ### ** Examples
> 
> data <- appendMatrixSize(col, dataFrame)
Error in unique.default(col) : unique() applies only to vectors
Calls: appendMatrixSize -> %in% -> unique -> unique.default
Execution halted
* checking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
```

**Comment by askv4694** [comment]
I've tried to fix this error but it seems I need more information about it. 
Is it possible that 'col' is not a vector? 
col parameter should be a vector:  col <- c("cg88888888", "cg11111111")

It's probably because I've documented incorrectly as in to provide an array but what I meant was a vector. 
I am sorry I shall fix documentation.

**Comment by merkys** [comment]
> I've tried to fix this error but it seems I need more information about it.
> Is it possible that 'col' is not a vector?
> col parameter should be a vector: col <- c("cg88888888", "cg11111111")

I think this is because `col` is not defined at all in the example provided here:
```
#' Append matrix rows
#'
#' @param col An array that has more positions that the matrix
#' @param data A dataframe which will be appended
#' @return Return appended dataframe
#' @examples
#' data <- appendMatrixSize(col, dataFrame)
#' @export
appendMatrixSize <- function(col, data){
```

**Comment by askv4694** [comment]
> > I've tried to fix this error but it seems I need more information about it.
> > Is it possible that 'col' is not a vector?
> > col parameter should be a vector: col <- c("cg88888888", "cg11111111")
> 
> I think this is because `col` is not defined at all in the example provided here:
> 
> ```
> #' Append matrix rows
> #'
> #' @param col An array that has more positions that the matrix
> #' @param data A dataframe which will be appended
> #' @return Return appended dataframe
> #' @examples
> #' data <- appendMatrixSize(col, dataFrame)
> #' @export
> appendMatrixSize <- function(col, data){
> ```

Oh that's why. Yes I should have provided more information about it. Well I did change it recently like this:
```
#' Append matrix rows
#'
#' @param col A vector that has different positions than the matrix
#' @param data A dataframe which will be appended
#' @return Return appended dataframe
#' @examples
#' data <- appendMatrixSize(col = c("cg11001140", "cg88888888"), dataFrame)
#' @export
appendMatrixSize <- function(col, data){
```
If that's enough for an example. 
This function is not necessary to use separately since it's called in makeConnections function.
But I did intend to let users have access to functions in case they wanted to process data more manually. 

I hope this helps.

**Comment by merkys** [comment]
I am still getting an error:
```
* checking examples ... ERROR
Running examples in ‘ewasvisual-Ex.R’ failed
The error most likely occurred in:

> ### Name: appendMatrixSize
> ### Title: Append matrix rows
> ### Aliases: appendMatrixSize
> 
> ### ** Examples
> 
> data <- appendMatrixSize(col = c("cg11001140", "cg88888888"), dataFrame)
Error in rownames(data) : object 'dataFrame' not found
Calls: appendMatrixSize -> %in% -> unique -> rownames
Execution halted
* checking PDF version of manual ... WARNING
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
```
However, as you say, these examples probably should not be executed during package checking. There is this [not run instruction](https://stackoverflow.com/questions/1454211/what-does-not-run-mean-in-r-help-pages) which seems to ignore running a particular example during package checking.

**Comment by askv4694** [comment]
I assumed that this was informational enough, but apparently, I should provide more information.

'dataFrame' is data that was returned from processData function. The function appendMatrixSize returns FALSE if col positions are no different from data (or dataFrame in example). 
If you want to check the function itself then I'd suggest this : 
```
data <-  appendMatrixSize(col = c("cg11001140", "cg88888888"), data)
```
Assuming that data contains results returned from processData function.
